# Dataset
dataset:
  dir: /path_to_dataset_dir/
  dir_tes: /path_to_dataset_dir_test/
  dataset: SEMANTIC8_processed
  num_points: 8192
  pillar_size: 8


# Network
network:
  model: KPConvSeg
  backend_conv:
    layer: FKAConv
    kernel_separation: false
  backend_search: SearchQuantized
  fusion_submodeldir: # only for the fusion model
    - path_to_modeldir_rgb
    - path_to_modeldir_noColor

# Training
training:
  savedir: path_to_save_directory
  batch_size: 16
  jitter: 0.4
  scaling_param: 0
  rgb: true
  rgb_dropout: false
  lr_start: 0.001
  training_steps: 1000
  validation_steps: 50
  epoch_nbr: 100
  weights: false

# Testing
test:
  step: 2
  batch_size: 16
  savepts: false
  savepreds: false

# misc
misc:
  device: cuda
  disable_tqdm: false
  threads: 4